modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="hack_client_mod"
version="1.0.3"
displayName="My Hack Client Mod"
displayURL="https://youtube.com/channel/UCp1744QlVdG-UJegGb-kxoQ?si=qOzey6A4f8AiDfVg"
credits="This mod is server-side. It will not work on other servers."
authors="Kimohpang"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.hack_client_mod]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.hack_client_mod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration